import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
    alias(libs.plugins.hilt)
    alias(libs.plugins.baselineprofile)
}

android {
    namespace = "com.wardrobe.app"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.wardrobe.app"
        minSdk = 26
        targetSdk = 36
        versionCode = 1
        versionName = "0.1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables { useSupportLibrary = true }
    }

    // Release signing reads from a local, gitignored keystore.properties file so no
    // secret ever lands in source control. See app/keystore.properties.example.
    val keystorePropertiesFile = rootProject.file("keystore.properties")
    val keystoreProperties =
        Properties().apply {
            if (keystorePropertiesFile.exists()) {
                keystorePropertiesFile.inputStream().use { load(it) }
            }
        }

    signingConfigs {
        create("release") {
            if (keystorePropertiesFile.exists()) {
                storeFile = file(keystoreProperties.getProperty("storeFile"))
                storePassword = keystoreProperties.getProperty("storePassword")
                keyAlias = keystoreProperties.getProperty("keyAlias")
                keyPassword = keystoreProperties.getProperty("keyPassword")
            }
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix = ".debug"
            isDebuggable = true
        }
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            // Falls back to the debug signing config when no keystore.properties is
            // present, so `assembleRelease` still builds locally without secrets —
            // it just isn't Play-Store-signed. Verified explicitly in Phase 2's
            // build checklist rather than left to fail silently.
            if (keystorePropertiesFile.exists()) {
                signingConfig = signingConfigs.getByName("release")
            } else {
                signingConfig = signingConfigs.getByName("debug")
            }
        }
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    testOptions {
        unitTests {
            isIncludeAndroidResources = true
        }
    }

    lint {
        // local.properties is machine-specific, gitignored, and normally
        // regenerated by Android Studio per developer machine — it isn't meant
        // to be a portable, checked-in file, so PropertyEscape's portability
        // warning about its Windows path doesn't apply. It's also a false
        // positive in practice: it still fires on a fully correctly-escaped
        // value (verified by trying that first before disabling anything).
        disable += "PropertyEscape"

        // targetSdk/compileSdk are capped at 36, not the newly-available 37,
        // because the SDK platform installed locally stops at 36.1 and several
        // AndroidX libraries' latest releases now require compileSdk 37 (see
        // the version catalog's comments on coreKtx/lifecycle/
        // hiltNavigationCompose — each was pinned back one minor specifically
        // for this). Bumping compileSdk without those libraries bumping too
        // would just trade this warning for a hard AAR-metadata build failure.
        disable += "OldTargetApi"

        // AGP 9.3.1 and newer coreKtx/lifecycle/hilt-navigation-compose patch
        // releases exist, per lint — a genuinely current, deliberately-pinned
        // toolchain, not a stale one: see the version catalog's comments for
        // exactly why each one is held back (compileSdk-37 requirements this
        // project can't yet satisfy, or a Kotlin-2.4-metadata compatibility
        // constraint). Re-check these when platform 37 is installed locally.
        disable += "AndroidGradlePluginVersion"
        disable += "GradleDependency"

        // Lint suggests merging mipmap-anydpi-v26 into a bare mipmap-anydpi
        // since minSdk is already 26. Verified empirically that AAPT2 rejects
        // that: it doesn't resolve `anydpi` as a valid qualifier without a
        // paired version qualifier, so `mipmap/ic_launcher` fails to resolve
        // at all with the "obsolete" folder renamed. Keeping `-v26` on this
        // folder is a correctness requirement, not an oversight.
        disable += "ObsoleteSdkInt"

        abortOnError = true
    }
}

kotlin {
    jvmToolchain(21)
}

dependencies {
    // Core module wiring — app is the composition root: it depends on every
    // feature and on core:data so Hilt can bind domain interfaces to implementations.
    implementation(project(":core:model"))
    implementation(project(":core:domain"))
    implementation(project(":core:common"))
    implementation(project(":core:data"))
    implementation(project(":core:designsystem"))
    implementation(project(":core:ui"))

    implementation(project(":feature:closet"))
    implementation(project(":feature:outfits"))
    implementation(project(":feature:calendar"))
    implementation(project(":feature:stats"))
    implementation(project(":feature:wishlist"))
    implementation(project(":feature:trips"))
    implementation(project(":feature:settings"))
    implementation(project(":feature:widget"))
    implementation(project(":feature:tryon"))
    implementation(project(":feature:capture"))
    implementation(project(":feature:onboarding"))

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.runtime.compose)

    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    debugImplementation(libs.androidx.compose.ui.tooling)

    implementation(libs.androidx.navigation.compose)
    implementation(libs.kotlinx.serialization.json)

    // WardrobeApplication implements SingletonImageLoader.Factory (Phase 5b) so
    // every AsyncImage in the app shares one bounded-cache ImageLoader — see
    // core:ui's WardrobeImageLoaderFactory.
    implementation(libs.coil.compose)

    implementation(libs.hilt.android)
    ksp(libs.hilt.android.compiler)
    // M16 — WardrobeNavHost's own onboarding-gate ViewModel (OnboardingGateViewModel)
    // is the first ViewModel `app` itself resolves via hiltViewModel(), not
    // just a feature module.
    implementation(libs.androidx.hilt.navigation.compose)

    implementation(libs.androidx.work.runtime.ktx)
    implementation(libs.androidx.hilt.work)
    implementation(libs.androidx.profileinstaller)

    // Generated by :benchmark (androidx.baselineprofile plugin); requires a
    // connected device/emulator to actually run — see benchmark/README.md.
    baselineProfile(project(":benchmark"))

    testImplementation(project(":core:testing"))
    testImplementation(libs.junit4)
    testImplementation(libs.kotlinx.coroutines.test)

    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.androidx.test.espresso.core)
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    androidTestImplementation(libs.hilt.android.testing)
    kspAndroidTest(libs.hilt.android.compiler)
    debugImplementation(libs.androidx.compose.ui.test.manifest)
}
